server:
  port: 8080

resource:
  path: src\main\resources\ontologies\
    uco2: src\main\resources\ontologies\uco2\
    cve: src\main\resources\ontologies\actual_cve\

journal:
  file:
    location: C:\\your\\example\\path\\blazegraph\\example.jnl