server:
  port: 8080

cross:
  origin:
    resource: http://147.175.121.153

resource:
  path:
    uco2: src\main\resources\ontologies\uco2\
    cve: src\main\resources\ontologies\actual_cve\

journal:
  file:
    location: C:\\your\\example\\path\\blazegraph\\example.jnl